### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by panda2134** [fuck-castic/fuck-castic.github.io#3]
似乎《基于一致性哈希算法的区块链优化模型》原论文没那么离谱，至少看上去就是普通高中生的水平。。。不知道为什么要挂

论文知网有

**Comment by panda2134** [comment]
而且发的也不是什么顶级期刊，说明这玩意实际价值有限、、、
另外本人查了一下 作者是NOI2019Ag 而不是像您写的“多次noip获奖” 作为一个曾经的信竞选手 我觉得一个ag写出这种文章没什么问题 这个和小学生基因敲除还是有本质区别的

如果您有异议欢迎讨论

**Comment by fuck-castic** [comment]
感谢指正
